services:
  # Base de datos local
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # Backend (FastAPI)
  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://adminuser:password123@db:5432/postgres
    ports:
      - "8000:80" # Mapeamos puerto 80 del contenedor a 8000 local
    depends_on:
      - db

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:80 # Nombre del servicio en docker-compose
    ports:
      - "3000:80"
    depends_on:
      - backend
